esphome:
  name: ${device_name}

esp8266:
  board: esp12e
  early_pin_init: false

# Device Specific Config

logger:
  baud_rate: 0 # (UART logging interferes with cse7766)
  logs:
    sensor: DEBUG # (Overide any global setting, to VERBOSE will spamming the cse7766 sensors)

uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_devicename}: Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "${friendly_devicename}: Status"

sensor:
  - platform: wifi_signal
    name: "${friendly_devicename}: WiFi Signal"
    update_interval: 60s
  - platform: cse7766
    current:
      name: "${friendly_devicename}: Current"
      accuracy_decimals: 2
      filters:
        - throttle_average: 60s
    voltage:
      name: "${friendly_devicename}: Voltage"
      accuracy_decimals: 2
      filters:
        - throttle_average: 60s
    power:
      name: "${friendly_devicename}: Power"
      accuracy_decimals: 2
      id: my_power
      filters:
        - throttle_average: 60s
    energy:
      name: "${friendly_devicename}: Energy"
      accuracy_decimals: 2
      filters:
        - throttle: 60s
    apparent_power: #(only available with version 2024.3.0 or greater)
      name: "${friendly_devicename}: Apparent Power"
      filters:
        - throttle_average: 60s
    power_factor: #(only available with version 2024.3.0 or greater)
      name: "${friendly_devicename}: Power Factor"
      accuracy_decimals: 2
      filters:
        - throttle_average: 60s

  - platform: total_daily_energy #(Optional, not specific to cse7766)
    name: "${friendly_devicename}: Daily Energy"
    power_id: my_power
    accuracy_decimals: 2

switch:
  - platform: gpio
    name: "${friendly_devicename}: Relay"
    pin: GPIO12
    id: relay
    restore_mode: "${restore_state}" # Powering the relay may cause damage or instability when the programmer is supplying Vcc.

time:
  - platform: sntp #(required for total_daily_energy)
    id: my_time

status_led:
  pin:
    number: GPIO13
    inverted: True

<<: !include wifi-sonoff.yaml
